name: 'churn_prediction'
version: '1.0.0'
config-version: 2

profile: 'churn_prediction'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  churn_prediction:
    staging:
      +materialized: view
      +schema: staging
    intermediate:
      +materialized: view
      +schema: intermediate
    marts:
      +materialized: table
      +schema: marts

snapshots:
  churn_prediction:
    +target-schema: snapshots

vars:
  start_date: '2024-01-01'
  end_date: '2024-12-31'

